DATA_DIR = 'dataset'
LOG_DIR = 'logs'
RESULT_DIR = 'results'
CHECKPOINT_DIR = 'training_checkpoints'
MODEL_DIR = 'models'

PRETRAIN_PREFIX = 'pretrain_'
GENERATOR_NAME = 'generator'
DISCRIMINATOR_NAME = 'discriminator'
SOURCE_DOMAIN = 'A'
TARGET_DOMAIN = 'B'

IMG_SIZE = 256
BATCH_SIZE = 4
SAMPLE_SIZE = 8
CONTENT_LAMBDA = .4
STYLE_LAMBDA = 25.
G_ADV_LAMBDA = 8.
D_ADV_LAMBDA = 1

GENERATOR_LR = 4e-5
DISCRIMINATOR_LR = 1.5e-5
PRETRAIN_LEARNING_RATE = 2e-4
EPOCHS = 32
PRETRAIN_EPOCHS = 2
PRETRAIN_SAVING_EPOCHS = 1
PRETRAIN_REPORTING_STEPS = 100
REPORTING_STEPS = 100
